kind = "mobile"
previewPath = "/"
title = "LinkIt 링킷"
version = "1.0.0"
id = "artifacts/linkit"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22734

[services.development]
run = "pnpm --filter @workspace/linkit run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/linkit", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/linkit", "run", "serve" ]

[services.env]
PORT = "22734"
BASE_PATH = "/"
